export const boardGeneratorArray = [
  {
    id: "br-a8",
    pieceClass: "square-white",

    src: "pieces/br.png",
    alt: "tower",
    number: 8,
    letterClass: null,
    numberClass: "eight",
  },
  {
    id: "bn-b8",
    pieceClass: "square-green",

    src: "pieces/bn.png",
    alt: "a knight",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bb-c8",
    pieceClass: "square-white",

    src: "pieces/bb.png",
    alt: "Holy guy",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bq-d8",
    pieceClass: "square-green",

    src: "pieces/bq.png",
    alt: "Happy wife, happy life",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bk-e8",
    pieceClass: "square-white",

    src: "pieces/bk.png",
    alt: "Royalty",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bb-f8",
    pieceClass: "square-green",

    src: "pieces/bb.png",
    alt: "Holy guy x2",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bn-g8",
    pieceClass: "square-white",

    src: "pieces/bn.png",
    alt: "headless horseman",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "br-h8",
    pieceClass: "square-green",

    src: "pieces/br.png",
    alt: "twin towers",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-a7",
    pieceClass: "square-green",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: 7,
    letterClass: null,
    numberClass: "seven",
  },
  {
    id: "bp-b2",
    pieceClass: "square-white",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-c7",
    pieceClass: "square-green",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-d7",
    pieceClass: "square-white",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-e7",
    pieceClass: "square-green",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-f7",
    pieceClass: "square-white",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-g7",
    pieceClass: "square-green",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "bp-h7",
    pieceClass: "square-white",

    src: "pieces/bp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },

  /* -------------- NO PIECES -------------------- */

  {
    id: "a6",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: 6,
    letterClass: null,
    numberClass: "six",
  },
  {
    id: "b6",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "c6",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "d6",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "e6",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "f6",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "g6",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "h6",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },

  {
    id: "a5",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: 5,
    letterClass: null,
    numberClass: "five",
  },

  {
    id: "b5",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "c5",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "d5",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "e5",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "f5",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "g5",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "h5",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "a4",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: 4,
    letterClass: null,
    numberClass: "four",
  },
  {
    id: "b4",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "c4",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "d4",
    pieceClass: "square-green",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "e4",
    pieceClass: "square-white",

    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "f4",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "g4",
    pieceClass: "square-white",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "h4",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "a3",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: 3,
    letterClass: null,
    numberClass: "three",
  },

  {
    id: "b3",
    pieceClass: "square-white",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "c3",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "d3",
    pieceClass: "square-white",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "e3",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "f3",
    pieceClass: "square-white",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "g3",
    pieceClass: "square-green",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "h3",
    pieceClass: "square-white",
    src: null,
    alt: null,
    number: null,
    letterClass: null,
    numberClass: null,
  },

  /* ------------- WHITE PIECES --------------- */

  {
    id: "wp-a2",
    pieceClass: "square-white",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: 2,
    letterClass: null,
    numberClass: "two",
  },
  {
    id: "wp-b2",
    pieceClass: "square-green",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-c2",
    pieceClass: "square-white",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-d2",
    pieceClass: "square-green",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-e2",
    pieceClass: "square-white",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-f2",
    pieceClass: "square-green",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-g2",
    pieceClass: "square-white",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },
  {
    id: "wp-h2",
    pieceClass: "square-green",
    src: "pieces/wp.png",
    alt: "Pawn",
    number: null,
    letterClass: null,
    numberClass: null,
  },

  {
    id: "wr-1",
    pieceClass: "square-green",
    src: "pieces/wr.png",
    alt: "tower",
    number: 1,
    letterClass: "a",
    numberClass: "one",
  },
  {
    id: "wn-1",
    pieceClass: "square-white",
    src: "pieces/wn.png",
    alt: "a knight",
    number: null,
    letterClass: "b",
    numberClass: null,
  },
  {
    id: "wb-1",
    pieceClass: "square-green",
    src: "pieces/wb.png",
    alt: "Holy guy",
    number: null,
    letterClass: "c",
    numberClass: null,
  },
  {
    id: "wq-1",
    pieceClass: "square-white",
    src: "pieces/wq.png",
    alt: "Happy wife, happy life",
    number: null,
    letterClass: "d",
    numberClass: null,
  },
  {
    id: "wk-1",
    pieceClass: "square-green",
    src: "pieces/wk.png",
    alt: "Royalty",
    number: null,
    letterClass: "e",
    numberClass: null,
  },
  {
    id: "wb-1",
    pieceClass: "square-white",
    src: "pieces/wb.png",
    alt: "Holy guy x2",
    number: null,
    letterClass: "f",
    numberClass: null,
  },
  {
    id: "wn-1",
    pieceClass: "square-green",
    src: "pieces/wn.png",
    alt: "headless horseman",
    number: null,
    letterClass: "g",
    numberClass: null,
  },
  {
    id: "wr-1",
    pieceClass: "square-white",
    src: "pieces/wr.png",
    alt: "twin towers",
    number: null,
    letterClass: "h",
    numberClass: null,
  },
];
